### ISSUE TITLE
Documentation README 수정 관련 요구 사항

### ISSUE THREAD

**Issue by Cyy92** [DigitalCompanion-KETI/DCFramework#11]
--- Hello DCF ---
2. 컴포넌트 생성
- function name에 대문자가 포함되어 있으면 오류발생(function name can only contain a-z, 0-9 and dashes)
- 컴포넌트 생성 시, config.yaml 파일도 같이 생성되는데, 이에 대한 설명이 들어가면 좋을 것 같습니다. 
  (config.yaml 파일이 무엇인지? 이 부분은 제가 예전에 만들어 놓은 readme에 명시되어 있습니다.)
- <DCF에 들어오는 요청이 들어오고 처리되는 스크립트입니다.> 이 부분에서 말이 조금 이상한 것 같아서 바꾸면 좋을 것 같습니다.

3. 배포 확인
- function status가 ready 상태가 되기 까지 시간이 걸리는 이유를 명시하면 좋을 것 같습니다. 
  (이 부분도 제가 예전에 만든 readme에 있습니다.) 

5. 컴포넌트 호출
- 컴포넌트 생성할 때 function name = hellodcf 이기 때문에 echo-service를 hellodcf로 수정하면 좋을 것 같습니다.
- '컴포넌트를 호출하는 방법이 2가지이다' 라는 것을 명시하면 좋을 것 같습니다. 
  (dcf function call function_name -> STDIN / Stop)
  (echo ~~ | dcf function call function_name)

--- SSD ---
Install SSD 구현체 
- models 폴더 안에 ssd 폴더 생성
  (mkdir models, mkdir ssd 라고 명시되어서 처음에 models 폴더 따로, ssd 폴더 따로 만들었는데 코드상으로는 
  models 폴더 안 ssd 폴더의 predict를 import 하는 구조여서 시간이 좀 걸렸습니다.)

function status check 
- function 오타

requirements.txt에 대한 내용이 필요할 것 같습니다. (tensorflow==1.11.0, pillow, matplotlib ...)

**Comment by ssaru** [comment]
- <DCF에 들어오는 요청이 들어오고 처리되는 스크립트입니다.> 이 부분에서 말이 조금 이상한 것 같아서 바꾸면 좋을 것 같습니다.
: 이부분은 어떻게 바꾸면 좋을까요?! ->  DCF로 들어오는 요청을 처리해주는 스크립트 입니다.

- 컴포넌트 생성 시, config.yaml 파일도 같이 생성되는데, 이에 대한 설명이 들어가면 좋을 것 같습니다.
- function status가 ready 상태가 되기 까지 시간이 걸리는 이유를 명시하면 좋을 것 같습니다.
- 컴포넌트 생성할 때 function name = hellodcf 이기 때문에 echo-service를 hellodcf로 수정하면 좋을 것 같습니다.
- models 폴더 안에 ssd 폴더 생성
- function 오타
- requirements.txt 내용 추가

해당 부분은 확인하도록 하겠습니다.
