### ISSUE TITLE
[Documents] DCF CLI, HelloDCF 문서 보강

### ISSUE THREAD

**Issue by ssaru** [DigitalCompanion-KETI/DCFramework#14]

**Comment by Cyy92** [comment]
[Documents] DCF CLI, Hello DCF 문서 보강 완료하였습니다. 확인부탁드립니다.

**Comment by ssaru** [comment]
`5. 컴포넌트 호출`에서 파이프라이닝을 이용한 호출예시를 코드레벨로 작성해주면 사용자 입장에서 큰 도움이 될 것 같습니다. echo를 사용한 방법은 직관적으로 확인할 수 있지만, 파이프라이닝 예시는 따로 없어서 사용하기 어려울 수 있을 것 같습니다.
